### ISSUE TITLE
Python

### ISSUE THREAD

**Issue by Torrer** [Ground-Zerro/DomainMapper#11]
What version of Python do I need?

**Comment by CodexHub58** [comment]
**Just use one of this Python versions:**
Python 3.7 (released in 2018)
Python 3.8 (released in 2019)
Python 3.9 (released in 2020)
Python 3.10 (released in 2021)

**Comment by Ground-Zerro** [comment]
> What version of Python do I need?
Hi!
I have Python 3.12.3 installed.

[CodexHub58](https://github.com/CodexHub58) says these will fit, too:
> **Just use one of this Python versions:**
> Python 3.7 (released in 2018)
> Python 3.8 (released in 2019)
> Python 3.9 (released in 2020)
> Python 3.10 (released in 2021)
