### ISSUE TITLE
Неправильно указан диапазон IP-адресов в CIDR-формате

### ISSUE THREAD

**Issue by CoolAller** [Ground-Zerro/DomainMapper#12]
Неправильно указан диапазон IP-адресов в CIDR-формате.

Как пример  взял из вашего списка два диапазона Google LLC в CIDR-формате:
108.177.14.138/32
108.177.14.113/32

Эти диапазоны IP-адресов включают по одному адресу, а именно 108.177.14.138 и 108.177.14.113. 

В действительности же они входят в подсеть с диапазоном 108.177.0.0/17 с роутом 108.177.14.0/24.

Сервис, которому принадлежат данные ip адреса, использует весь диапазон подсети 108.177.14.0 - 108.177.14.255. 

Таким образом, нецелесообразно добавлять только два ip адреса, так как ресурс все равно не будет нормально работать в виду балансировки нагрузки серверов в данном диапазоне. Указывать нужно как минимум весь диапазон 108.177.14.0/24.

По поводу списков доменов, в списке присутствуют псевдонимы (алиасы) и их канонические имена, по сути это просто дубли.

Например, из списка YouTube:
rr6.sn-jvhnu5g-n8vy.googlevideo.com
rr6---sn-jvhnu5g-n8vy.googlevideo.com

Обе эти записи это один домен, так как:
rr6---sn-jvhnu5g-c35d.googlevideo.com	 canonical name = rr6.sn-jvhnu5g-c35d.googlevideo.com

Не совсем понятно как вы собираете имена этих доменов, так как они соответствуют некоторому количеству серверов в зависимости от вашего личного местоположения, сетевой инфраструктуры вашего провайдера, а также загрузки этих серверов в разный момент времени. Другими словами, например, если вы находитесь в Калининграде, то вам будут выдаваться сервера как наиболее близкие к вам: rr18, а для тех, кто находится где-нибудь в Москве: rr3. Ситуация также меняется в зависимости от вашего VPN и его географического положения, маршрутов и т.д.

**Comment by Ground-Zerro** [comment]
Да, я знаю о такой проблеме.
Механизм работы DM простой: DNS сервер разрешает IP-адрес указанного в списке домена, полученный "здесь и сейчас" результат записывается в файл.
DM не имеет средств аналитики и не обращается к ресурсам, содержащим информацию подобного рода чтобы опереться на нее и скорректировать результат. Это довольно простой и "топорный" инструмент.
Именно по этим причинам логическим продолжением DomainMapper стал [DNS-RouteSync-Navigator](https://github.com/Ground-Zerro/DNS-RouteSync-Navigator), который работает в реальном времени.
Причины по которым люди продолжают пользоваться DM даже учитывая его ограниченность мне не известны, видимо он подходит для реализации каких-то своих узконаправленных задач.

Ваше дополнения я разжевывал уже не в одном закрытом коммите.

**Comment by CoolAller** [comment]
[Ground-Zerro](https://github.com/Ground-Zerro) пользуясь случем, могу я задать вам вопрос относительно [DNS-RouteSync-Navigator](https://github.com/Ground-Zerro/DNS-RouteSync-Navigator)? ПРавильно ли я понимаю, что ответ на DNS запрос приходит раньше, чем происходит добавление маршрута в таблицу маршрутизации на роутере? Если так, то только при повторном обращении к доменному имени произойдет его перенаправление в туннель?

**Comment by Ground-Zerro** [comment]
> [Ground-Zerro](https://github.com/Ground-Zerro) благодарю за ответ, пользуясь случем, могу я задать вам вопрос относительно [DNS-RouteSync-Navigator](https://github.com/Ground-Zerro/DNS-RouteSync-Navigator)? Правильно ли я понимаю, что ответ на DNS запрос приходит раньше, чем происходит добавление маршрута в таблицу маршрутизации на роутере и он будет направлен на дефолтный шлюз? Если так, то только при повторном обращении к доменному имени произойдет его перенаправление в туннель?

Именно так.
Изначально DNS ответ придерживался до проверки домена на фильтрацию и добавление маршрута, но это очень сильно увеличивало задержку DNS ответа для хоста. Поэтому механизм был изменен, DNS сервер работает с хостом напрямую вопрос-ответ, а фильтрация и добавление маршрута происходит уже параллельно. Таким способом удалось снизить время ответа на DNS запрос хоста фактически до пинга между хостом и DNS резольвером.
Опять же это своего рода костыль, который как и DM родился из отсутствия возможности установить на роутер entware.
