### ISSUE TITLE
Как использовать config.ini?

### ISSUE THREAD

**Issue by ITNetSystem** [Ground-Zerro/DomainMapper#14]
отредактировал config.ini, как заставить скрипт его использовать? Хочу адрес листы для mikrotik

**Comment by Ground-Zerro** [comment]
> отредактировал config.ini, как заставить скрипт его использовать? Хочу адрес листы для mikrotik

Положить main.py и config.ini  в один каталог и запустить main.py оттуда же.

Linux:
Если скажем, main.py лежит в /dns/main.py, а запускать его из консоли командной python3 "/dns/main.py" находясь например /root/ то конфиг не подцепится.

Windows:
Аналогично.
+
При использовании батника для запуска Domain Mapper под windows из папки "Windows" репозитория или запуска скрипта используя команды, указанные там же - config.ini не будет учитываться никогда.

При старте скрипт всегда сообщает загружен config.ini или нет:
`Ошибка загрузки config.ini: [Errno 2] No such file or directory: 'config.ini' Используются настройки 'по умолчанию'.`
или
`Загружена конфигурация из config.ini:
Сервисы для проверки: Youtube, Facebook
Использовать DNS сервер: [1]
Количество одновременных запросов к одному DNS серверу: 200
Фильтр IP-адресов Cloudflare: включен
Сохранить результаты в файл: domain-ip-resolve.txt
Формат сохранения: CLI Mikrotik firewall
Шлюз/Имя интерфейса для маршрутов: 0.0.0.0
Имя списка для Mikrotik firewall: mikrotik
Выполнить по завершению: не указано`

Если в config.ini что-то заполнено неправильно скрипт выдаст ошибку по ходу выполнения.
