### ISSUE TITLE
add_static_route

### ISSUE THREAD

**Issue by JD99** [Ground-Zerro/DomainMapper#15]
modem.add_static_route(comment="add", host=ip, interface=interface)  

Core::Configurator: ip route: execute denied [http/rci].
Core::Configurator: system: execute denied [http/rci].
Core::Configurator: system configuration save: execute denied [http/rci].

**Comment by Ground-Zerro** [comment]
I'm sorry I didn't have time to read and absorb the question.
What was eventually done and what purpose does it now serve?
