### ISSUE TITLE
Проверяйте домены которые добавляете

### ISSUE THREAD

**Issue by OmlineEditor** [Ground-Zerro/DomainMapper#19]
Откуда для тиктока появились в списке эти домены? Они вообще не розолвятся и не имеют IP или это магазин огурцов. 

kai-tiktok.com - помер
khan.vip - помер
lumpoo22.tk - Вообще на бесплатном домене ".tk"
primelocation.vip - Припаркован
ryanlucas.net - редиректит на магазин огурцов, к тиктоку не имеет отношения.

Думаю там есть еще лишние домены и не только для тиктока, вы их хоть проверяйте перед добавлением.

**Comment by Ground-Zerro** [comment]
> kai-tiktok.com - помер
> khan.vip - помер
> lumpoo22.tk - Вообще на бесплатном домене ".tk"
> primelocation.vip - Припаркован
> ryanlucas.net - редиректит на магазин огурцов, к тиктоку не имеет отношения.

Спасибо, уберу их.

> Думаю там есть еще лишние домены и не только для тиктока, вы их хоть проверяйте перед добавлением.

tiktok список как и остальная часть списков сервисов взят у кого-то из репозитория и не выверялся тщательно.

Предложения по корректировке сервисов от пользователей поступали лишь дважды включая это.
Не, то чтобы автор против, автор какраз-таки "за", но из претензий без конкретных объяснений "что, как, почему" невозможно выжать хоть сколько-нибудь полезной информации для ее использования. Ваш пример - исключение, четко и понятно.

**Статусы списков Сервисов из репозитория:**
apple - не проверялся.
bing - проверен поверхностно.
facebook - проверен поверхностно.
google - проверен поверхностно.
instagram - проверен поверхностно.
netflix - проверен поверхностно.
openai  - создан исходя из личного опыта.
search-engines  - создан исходя из личного опыта.
tiktok.txt - проверен поверхностно.
ttruckers  - создан исходя из личного опыта.
twitter - проверен поверхностно.
**youtube** - уточнен, проверен, перепроверен и еще раз переуточнен.

Если есть еще уточнения, замечания - пишите.

**Comment by Ground-Zerro** [comment]
Удалены доменные имена Tik-Tok не соответствовавшие следующим критериям:
**Избыточность:** Если несколько доменов выполняют схожие функции или принадлежат к одному и тому же сервису.
**Устаревшие или неактивные домены:** Если домены были признаны устаревшими или больше не использовались для обеспечения работы приложения.
**Локальные или тестовые домены:** Домены, используемые исключительно для внутреннего тестирования или локальных сетей, если они не связаны с публичными сервисами.
**Нарушение правил маршрутизации:** Домены, которые могут создавать проблемы при маршрутизации трафика или нарушают правила сетевой безопасности.

Если есть дополнения, замечания - напишите пожалуйста.
