### ISSUE TITLE
docker container

### ISSUE THREAD

**Issue by andrejs82git** [Ground-Zerro/DomainMapper#21]
Hi!
Thanks for your application!

Please, crete Dockerfile, or maybe dockerhub image for using soft.

**Comment by andrejs82git** [comment]
Hi!

[0001-add-docker-support.patch](https://github.com/user-attachments/files/16898494/0001-add-docker-support.patch)

Patch with for using docker.

Thanks!

**Comment by andrejs82git** [comment]
Привет!

Мой случай такой. У меня есть удаленная машина к которой я подключась через ssh. 
Там у меня установлена программа, которая помогает ускорить ютуб.
Работает через докерконтейнер.

В целом, на мой взгляд, лучше когда программы запускаются в изолированной среде. 
А также, когда среда запуска уже подготовлена для программы.

В целом хотелось бы иметь такой сценарий:
- Делаю git clone . 
- Далее запускаю простой bash который соберет Dockerfile и запустит программу. 
- Далее всё как обычно.

**Comment by Wonderkot** [comment]
@andrejs82git 
Посмотри тут в сторону конфига, в ридми он описан. Ты можешь его отдельно у себя создать, написать свой докер файл. В нем уже опиши гит клон, прокинь туда свой конфиг и запускай там python main.py --config

**Comment by MrEagle123** [comment]
apt update
apt install git

Установить Docker, если не установлен:
curl -fsSL https://get.docker.com -o get-docker.sh
sh ./get-docker.sh

git clone https://github.com/Ground-Zerro/DomainMapper.git

Создать dockerfile
mcedit dockerfile

Содержимое dockerfile:
FROM ubuntu:jammy
WORKDIR /app
ADD ./DomainMapper /app
RUN apt-get update -y
RUN apt-get install python3-pip -y
RUN pip3 install -r requirements.txt
CMD ["python3", "main.py"]

echo test > ./domain-ip-resolve.txt

Собрать docker образ
docker build -t domainmapper .

Запустить docker контейнер
docker run -v ./domain-ip-resolve.txt:/app/domain-ip-resolve.txt -it domainmapper

Выбрать нужные опции, дождаться окончания работы скрипта, забрать результат из файла ./domain-ip-resolve.txt в текущей папке.

Для повторного запуска выполнить еще раз команду:
docker run -v ./domain-ip-resolve.txt:/app/domain-ip-resolve.txt -it domainmapper

**Comment by Ground-Zerro** [comment]
@MrEagle123 @andrejs82git

```
curl -L -s "https://raw.githubusercontent.com/Ground-Zerro/DomainMapper/refs/heads/main/dm-docker.sh" > /tmp/dm-docker.sh && chmod +x /tmp/dm-docker.sh && sh /tmp/dm-docker.sh
```
