### ISSUE TITLE
Instagram

### ISSUE THREAD

**Issue by SEModer** [Ground-Zerro/DomainMapper#22]
Прошу добавить в список DNS 
instagram.fkiv7-1.fna.fbcdn.net

Зачем добавлен яндекс в поисковики?

Можно ли тогда сделать список исключений? Ибо как я понимаю, все домены вытягиваются с этого репо, а не используются файлы в папке platform.

**Comment by Ground-Zerro** [comment]
> instagram.fkiv7-1.fna.fbcdn.net

Добавлен.


> Зачем добавлен яндекс в поисковики?

Чтобы при необходимости завернуть трафик к ним и получить поисковую выдачу для целевой страны.

А есть какой-то смысл заворачивать трафик для bing и оставлять его прямым для например google?

Хотя yandex.ru не поисковик как таковой теперь и ведет на дзен..


> как я понимаю, все домены вытягиваются с этого репо, а не используются файлы в папке platform.

Да.
Списки всегда вели в репозиторий с самой первой публикации кода.
Stand Alone версии нет.


> Можно ли тогда сделать список исключений?
Есть custom-dns-list для собственных списков. Можно сложить все что нужно туда и разрешать его отдельно от остальных.
