### ISSUE TITLE
Добавить домены для GitHub Copilot

### ISSUE THREAD

**Issue by aspirisen** [Ground-Zerro/DomainMapper#23]
Если я правильно понял, то необходимые url можно найти здесь https://docs.github.com/en/copilot/managing-copilot/managing-github-copilot-in-your-organization/configuring-your-proxy-server-or-firewall-for-copilot

**Comment by Ground-Zerro** [comment]
> Если я правильно понял, то необходимые url можно найти здесь

Идея интересная, но есть несколько вопросов.

Например github.com/login/* добавить не получится т.к. это URL а DNS сервер может разрешить только домен:
`*** UnKnown не удалось найти github.com/login/: Non-existent domain`
если добавить в список домен github.com то полностью весь трафик к гитхаб пойдет через туннель.

Тоже самое касается следующих URL:
api.github.com/copilot_internal/*
copilot-telemetry.githubusercontent.com/telemetry
*.githubcopilot.com

Если это не смущает и "Ок" - то добавлю отдельным списком.

**Comment by aspirisen** [comment]
Хм, там может и не нужно все добавлять, проблема что при запуску расширения он как-то определяет местоположение (при включении обычного vpn который перенаправляет весь трафик такого сообщения нет)
Но как определить куда расширение ходит для проверки я не знаю
<img width="477" alt="image" src="https://github.com/user-attachments/assets/0e3b31bd-a2aa-4947-a558-de560681cfcb">

**Comment by SEModer** [comment]
Можно попробовать каким либо сниффером отловить куда ходит vscode
Например HTTP Debugger Pro, триала на 7 дней думаю будет достаточно проверить куда ходит по факту =)

**Comment by Ground-Zerro** [comment]
Добавил отдельным списком "Github Copilot".
Домены взял из руководства оп ссылке, попробуйте.
Если что-то поправить - отпишитесь.

**Comment by aspirisen** [comment]
@Ground-Zerro у меня такая ошибка 
```
Traceback (most recent call last):
  File "/Users/dima/Downloads/DomainMapper-main/main.py", line 515, in <module>
    asyncio.run(main())
  File "/Users/dima/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/dima/.pyenv/versions/3.12.2/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dima/.pyenv/versions/3.12.2/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/dima/Downloads/DomainMapper-main/main.py", line 480, in main
    response.raise_for_status()
  File "/Users/dima/.pyenv/versions/3.12.2/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://raw.githubusercontent.com/Ground-Zerro/DomainMapper/main/platforms/dns-github%EF%BF%BDopilot.txt'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
sys:1: RuntimeWarning: coroutine 'resolve_dns' was never awaited
```
