### ISSUE TITLE
Дополнительные домены для Facebook'a

### ISSUE THREAD

**Issue by SEModer** [Ground-Zerro/DomainMapper#24]
Прошу добавить доп. домены, спасибо.
scontent-ist1-2.xx.fbcdn.net
static.xx.fbcdn.net (возможно как дубль чего-то аналогичного, но всёже)
fbsbx.com
scontent.xx.fbcdn.net

**Comment by SEModer** [comment]
+ gateway.facebook.com

**Comment by Ground-Zerro** [comment]
Добавлено.
