### ISSUE TITLE
Возможность указания конфиг файла

### ISSUE THREAD

**Issue by Noksa** [Ground-Zerro/DomainMapper#25]
Добрый день.

Хочется иметь возможность генерировать несколько результатов используя разные конфиг-файлы.

Сейчас это не очень удобно делать, хотелось бы иметь возможность указать какой конфиг файл использовать через флаг\переменную\как-либо еще.

Спасибо

**Comment by Ground-Zerro** [comment]
Интересные идеи мне подкидывают последнее время!

Дайте подумать, я попробую это реализовать, только не обещаю, что очень быстро.

**Comment by Ground-Zerro** [comment]
Добавил, тестируйте.

Инфа об использовании в readme.

**Comment by Noksa** [comment]
Всё четко, спасибо за оперативность @Ground-Zerro <3
