### ISSUE TITLE
Возможность использовать дополнительные DNS сервера

### ISSUE THREAD

**Issue by Noksa** [Ground-Zerro/DomainMapper#26]
Добрый день.

Сейчас используются только ДНС сервера из файла `dnsdb` и системный.

Было бы здорово, если бы была возможность указать дополнительные ДНС сервера через которые надо резолвить адреса, по аналогии как мы можем указать имена в `custom-dns-list.txt`

**Comment by Ground-Zerro** [comment]
А какие-то очень кастомные DNS предполагаются или общедоступные?
Может полезней будет их добавить в `dnsdb` для всех?

Все больше склоняюсь к Stand alone версии, чтоб можно было скачать и крутить и списки и DNS сервера как угодно.
Её нет т.к. изначально делалось для себя, а после во главе угла встала идея чтоб было максимально просто и функционально для бОльшего числа пользователей.

**Comment by Noksa** [comment]
@Ground-Zerro благодарствую!

Будем дать кастомных :)

![image](https://github.com/user-attachments/assets/00531a8d-24ca-4efc-8bc2-fc2dd145c9fb)
