### ISSUE TITLE
Список исключений для маппинга

### ISSUE THREAD

**Issue by SEModer** [Ground-Zerro/DomainMapper#28]
Есть ли возможность реализовать список исключений?

То есть указываем список доменов/IP/подсетей в файле, которые нужно исключить из подсетей /16 /24. самое проблемное, потребуется пересчитывать маски для вычленения этих адресов и обдумать логику как их правильно обработать.

**Comment by Ground-Zerro** [comment]
Хм.
Может это проще сделать дополнительным скриптом? Типа постобработки.

Накидайте идею чуть подробней, что из какого файла брать, в какой форме, что нужно удалить и как в итоге должно выглядеть.

**Comment by sanich2019** [comment]
Добрый день.
"Исключить IP адреса Cloudflare из итогового списка?" - можете объяснить для чего эта опция?

**Comment by sanich2019** [comment]
Добрый день.
"Исключить IP адреса Cloudflare из итогового списка?" - можете объяснить для чего эта опция?

**Comment by sanich2019** [comment]
Добрый день.
"Исключить IP адреса Cloudflare из итогового списка?" - можете объяснить для чего эта опция?

 Ещё хотелось бы узнать как это работает и что в каком случае нужно выбирать?:
"Сгруппировать подсети
# опции:
# пустое значение - пользователю будет выведено меню выбора
# 16 - группировка подсетей до /16 (255.255.0.0)
# 24 - группировка подсетей до /24 (255.255.255.0)
# mix - /24 и /32 в одном файле
# no - оставить как есть"

И вот это;
"# адрес шлюза или имя интерфейса - используется при сохранении IP-адресов в 'win' и 'unix' формате"


Вобщем, было бы неплохо получить пояснения "для чайников" как я. В сети не ищется ничего на эту тему. Спасибо

**Comment by Ground-Zerro** [comment]
**Простых ответов нет, придётся потратить 5 минут на чтение.**
> "Исключить IP адреса Cloudflare из итогового списка?" - можете объяснить для чего эта опция?

Cloudflare — это сеть доставки контента (CDN) и поставщик услуг интернет-безопасности, который помогает ускорять и защищать веб-сайты, используя различные технологии, включая динамическое распределение трафика по географически разнесенным серверам.

Как работает Cloudflare:
Сеть CDN: Cloudflare имеет большое количество серверов по всему миру. Когда пользователь запрашивает доступ к ресурсу, Cloudflare направляет запрос на ближайший к пользователю сервер, что уменьшает задержки и увеличивает скорость загрузки.

Кэширование данных: Ресурсы (такие как изображения, скрипты и страницы) кэшируются на серверах Cloudflare, чтобы не запрашивать их каждый раз с исходного сервера, что снижает нагрузку и улучшает производительность.

**Когда вы отправляете DNS-запрос, условно к `resurs.com` он маршрутизируется на сервер Cloudflare, ближайший к вам.
Таким образом фиксировать IP адрес конкретного DNS имени бессмысленно - он всегда будет разный.**

**Почему IP-адрес DNS меняется:**
_Anycast сеть:_ Cloudflare использует Anycast, что позволяет одному IP-адресу принадлежать множеству серверов в разных частях мира. Система маршрутизации выбирает ближайший сервер, который будет отвечать на запрос, чтобы минимизировать задержку.

_Географическое распределение:_ IP-адрес может изменяться в зависимости от вашего местоположения. Когда вы отправляете DNS-запрос, он маршрутизируется на сервер Cloudflare, ближайший к вам. В результате DNS-ответ содержит IP-адрес ближайшего узла.

_Балансировка нагрузки:_ Чтобы эффективно распределить трафик и предотвратить перегрузки, Cloudflare может перенаправлять запросы на разные серверы в зависимости от их загруженности. Это также влияет на изменение IP-адресов в DNS.

_Меры безопасности:_ Изменение IP-адресов также помогает маскировать реальное местоположение серверов и усложняет для злоумышленников проведение целевых атак на ресурс.


> Ещё хотелось бы узнать как это работает и что в каком случае нужно выбирать?:
> "Сгруппировать подсети"

Группировка IP-адресов в подсети позволяет маршрутизаторам агрегировать маршруты, что сокращает количество записей в таблицах маршрутизации. Вместо того, чтобы хранить информацию о каждом отдельном IP-адресе, маршрутизаторы могут работать с сетевыми префиксами (например, /24 или /16), что снижает нагрузку на оборудование и ускоряет принятие решений по маршрутизации.
**Например если узлы в сети используют адреса из одного диапазона 192.168.1.0/24, маршрутизатору достаточно иметь одну запись о маршруте для этой сети, вместо 255 маршрутов для каждого отдельного IP-адреса.**
Что выбрать - каждый решает сам в зависимости от задачи, возможностей оборудования и личных предпочтений.


> И вот это;
> "# адрес шлюза или имя интерфейса - используется при сохранении IP-адресов в 'win' и 'unix' формате"

**Роутер (маршрутизатор) может иметь несколько подключений, например быть подключенным к нескольким провайдерам и VPN подключениям, каждое из которых имеет свой шлюз через который данные отправляются в сеть.**

Шлюз — это как "ворота" в другую сеть, через которые проходят данные. Когда компьютер хочет отправить информацию за пределы своей локальной сети (например, в интернет), он использует шлюз, чтобы передать данные дальше.

Маршрут нужен для того, чтобы компьютер знал, через какой шлюз передавать данные, чтобы они дошли до нужного IP-адреса или сети. То есть маршрут указывает, какие "ворота" использовать для отправки информации в определённую сеть или к определённому адресу.

**Comment by Ground-Zerro** [comment]
У меня тоже вопрос накопился: Скажи мил человек, как не зная ничего про IP, маршруты, DNS серверы, домены и т.д. ты оказался в этом репозитории и зачем тебе вообще DomainMapper?????

Не хочу уязвить и не пытаюсь обидеть, никто не обязан знать об этом если ему это не нужно, просто пытаюсь понять для чего в такой ситуации тебе понадобилась эта программа?

**Comment by sanich2019** [comment]
Благодарю за пояснения.

**Comment by sanich2019** [comment]
> У меня тоже вопрос накопился: Скажи мил человек, как не зная ничего про IP, маршруты, DNS серверы, домены и т.д. ты оказался в этом репозитории и зачем тебе вообще DomainMapper?????


Если этот вопрос мне, то объясняю: мне бы это всё ну совершенно не нужно было и жил бы я не тужил и дальше без этих знаний. Но угораздило меня родиться и вырасти в России...
