### ISSUE TITLE
Можно упростить конфигурацию для GitHub Copilot

### ISSUE THREAD

**Issue by aspirisen** [Ground-Zerro/DomainMapper#29]
Я попробовал маршруты copilot, все работает
Так же я попробовал уменьшить кол-во адресов в конфиге, и все продолжило работать

```
copilot-telemetry.githubusercontent.com
copilot-proxy.githubusercontent.com
githubcopilot.com
```

**Comment by Ground-Zerro** [comment]
@aspirisen Хорошо. Оставил эти три.
