### ISSUE TITLE
ip ranges twitch

### ISSUE THREAD

**Issue by shevernitskiy** [Ground-Zerro/DomainMapper#31]
Сделайте пожалуйста адреса для твича, похоже и до него добрались

**Comment by Ground-Zerro** [comment]
@shevernitskiy 
Не поступало подобной информации.

Платформа добавлена.

Если четь чем дополнить домены Твича - пишите (отдельной темой).

**Comment by shevernitskiy** [comment]
Провайдер Мегафон Домашний интеренет, можно по сервисам сбоев глянуть (у всех юзеров было). Симпотомы - не грузило видео, чат прям раз в 5 миг конектило.. Симптомы наталкивают на размышление.
Спасибо, что добавили, лучше подготовиться:)
