### ISSUE TITLE
Генератор конфига

### ISSUE THREAD

**Issue by shevernitskiy** [Ground-Zerro/DomainMapper#32]
Можно сделать мегапростой веб апп, например на streamlit, на котором можно будет выбрать сервисы и выходной формат.
По кнопочке будет генериться файл с нужными адресами и нужного формата (для кинетиков, для опенврт, или для вг)

**Comment by Ground-Zerro** [comment]
Привет!

Это предложение или запрос? ))

Наверняка кому-то это будет удобно, но я этого сделать не могу.

Если кто-то разработает и запустит то с удовольствием добавлю инструкцию и ссылку в описание.
