### ISSUE TITLE
Неверный ключ для торрентов в конфиге

### ISSUE THREAD

**Issue by Noksa** [Ground-Zerro/DomainMapper#34]
В config.ini:
```
# Tor-Truckers - торрент трекеры
```

По факту в `platformdb`:
```
Torrent Truckers
```

Если указать `Tor-Truckers` в `service =` то будет ошибка.

**Comment by Ground-Zerro** [comment]
Спасибо.
Такая же история с Search engines, забыл поправить.

Исправлено.
