### ISSUE TITLE
Не работает YouTube на мобильных устройствах Android

### ISSUE THREAD

**Issue by VadimB95** [Ground-Zerro/DomainMapper#35]
Спасибо за скрипт, на десктопе в браузере YouTube работает отлично. Однако, на андроид клиентах довольно долго грузятся экраны плюс вообще не работает просмотр видео. Также не работает ютуб и в браузере на мобилке. При этом если весь трафик пускать через VPN, то всё летает.

**Comment by Ground-Zerro** [comment]
Привет.

По этому поводу есть только догадки,
от простых:
- используемого в вашей локации GGC или какого-то другого необходимого для мобильного приложения DNS нет в списке.
- провайдер подменяет DNS.

до экзотических:
- при точечной маршрутизации на роутере мобильник  считает что по wi-fi интернет не доступен и переключается на интернет от сотового оператора.
- мобильное устройство по какой-то причине использует отличный от системного DNS сервер.
- используется ipv6 от провайдера.
и т.д. и т.п.

Однозначно только одно - проблема связана с конкретным устройством, а не с настройками роутера, маршрутами и т.п.

Если удастся выяснить причину - отпишитесь здесь пожалуйста.

**Comment by VadimB95** [comment]
К сожалению, мои познания о сетях довольно поверхностные, но есть желание докопаться до причины)

Сегодня немного поэкспериментировал:  на ноуте установлен Android эмулятор и сниффер траффика (Charles). На эмуле ютуб работает и при точечной маршрутизации и при прогоне всего трафика ноута через впн. Ну и что уже естественно, побродив немного по ютубу и посмотрев на какие адреса он ходит, убедился, что всё из этого в маршрутах прописано. 

При этом тут же рядом лежит физический девайс, который не работает) Получается, проблема именно на физическом девайсе. Завтра еще подключусь с физического девайса через сниффер, посмотрю что будет. 

Подскажи, что еще можно посмотреть?

**Comment by VadimB95** [comment]
После запуска traceroute до youtube.com на физическом девайсе увидел, что адрес резолвится в ipv6. Cтало очевидно, что проблема в этом. Нагуглилось, что андроид начиная с 10 версии вроде как по умолчанию использует ipv6. Для эксперимента включил в кинетике галку "Игнорировать DNSv6 интернет-провайдера", ютуб заработал. 
Не совсем понимаю, как это будет аффектить обычную повседневную работу в интернете, можешь что-то подсказать по этому поводу?

Плюс задам возможно глупый вопрос: статические маршруты для ipv6 вообще имеют смысл?

**Comment by Ground-Zerro** [comment]
@VadimB95 
ipv6 имеет приоритет перед ipv4 на всех устройствах, на ПК видимо он просто выключен.
Так сложилось что v6 не смотря на свой возраст и очевидные плюсы плохо распространен и изучен пользователями, системными администраторами и т.д., соответственно редко применяется и не всем софтом поддерживается - DomainMapper тому пример.
Когда речь заходит о настройке фаерволов его как правило вообще отключают ввиду чуть более сложной настройки.
Основной и очевидный его плюс - отсутствие NAT, для того кто с ним должен работать становится минусом в подобных случаях, хотя это совсем не так и просто нужно научиться с ним работать.

> статические маршруты для ipv6 вообще имеют смысл?

Имеют, если это необходимо, но можно и проигнорировать.

Мне вот например не хватает ipv6 от провайдера и я готов учиться с ним работать, но возможности такой нет.

А что за роутер?
Может будет правильней работать с таблицами маршрутизации основываясь на DNS запросах и маршрутизировать трафик прямо на роутере?
Я использую [это решение](https://taravasya.github.io/notes/keenetic/agh_keenetic), головомойки меньше, возни с доменами, маршрутами и т.п. По части требований к навыкам пользователя оно попроще остальных аналогичных. Там и ipv6 поддерживается, все что требуется - один раз настроить.

**Comment by VadimB95** [comment]
@Ground-Zerro Спасибо, попробую поковырять на неделе то, что по ссылке. Роутер Keenetic Ultra-1811

**Comment by Ground-Zerro** [comment]
@VadimB95 

> Keenetic Ultra-1811

Ну офигеть, целая Ультра!!!

Конечно нужно поковырять, крутить маршруты при таких возможностях железки это как из пушки по мухам...
