### ISSUE TITLE
ip ranges crunchyroll

### ISSUE THREAD

**Issue by Wonderkot** [Ground-Zerro/DomainMapper#39]
Здравствуйте, с недавного времени перестал нормально работать стриминговый сервис crunchyroll, есть возможность его добавить?

**Comment by Ground-Zerro** [comment]
Не нашел подробной информации о доменах сервиса, но совершенно точно, что он использует CDN cloudflare. Соответственно смысла резолвить его домены в IP нет, проще сразу кинуть все IP cloudflare через туннель.

https://www.cloudflare.com/ips/

```
103.21.244.0/22
103.22.200.0/22
103.31.4.0/22
104.16.0.0/13
104.24.0.0/14
108.162.192.0/18
131.0.72.0/22
141.101.64.0/18
162.158.0.0/15
172.64.0.0/13
173.245.48.0/20
188.114.96.0/20
190.93.240.0/20
197.234.240.0/22
198.41.128.0/17
```
