### ISSUE TITLE
Jetbrains

### ISSUE THREAD

**Issue by SocketSomeone** [Ground-Zerro/DomainMapper#40]
Недавно они обрубили всё, от обновлялок приложений и уже дошли до обновления расширений

**Comment by Ground-Zerro** [comment]
Принято в работу, но может затянуться. Сам сервис добавить не сложно, однако нужен список доменов и субдоменов. Пока нашел только эти:
```
jetbrains.com.cn
jb.gg
myjetbrains.com
jetbrains.com
intellij.net
```
Можете дополнить его, чтобы ускорить процесс.

**Comment by SocketSomeone** [comment]
```
download-cdn.jetbrains.com
```

Добавляю

**Comment by Ground-Zerro** [comment]
@SocketSomeone 

Jetbrains сервис добавлен.

Добавлены основные домены и субдомены jetbrains.com.
[Полный список](https://raw.githubusercontent.com/Ground-Zerro/DomainMapper/refs/heads/main/platforms/dns-jetbrains.txt)
Возможно для работы может понадобится что-то еще - пишите.

PS
`download.jetbrains.com` псевдоним `download-cdn.jetbrains.com`.

**Comment by bpystep** [comment]
@Ground-Zerro есть еще *.jetbrains.space, было бы круто добавить

https://www.jetbrains.com/space

**Comment by Ground-Zerro** [comment]
@bpystep 
Добавлено
awsproxy.pkg-cdn.jetbrains.space
byid.eu-1.jetbrains.space
byid.jetbrains.space
cloudfront.pkg-cdn.jetbrains.space
corona.jetbrains.space
dc.jetbrains.space
element.jetbrains.space
eu-1.jetbrains.space
jetbrains.space
justtoplay.jetbrains.space
maven.jetbrains.space
maven.pkg.jetbrains.space
ngenix.assets.service.jetbrains.space
pkg-cdn.jetbrains.space
pkg.eu-1.jetbrains.space
registry.eu-1.jetbrains.space
registry.jetbrains.space
ruhlaender.jetbrains.space
space-cdn.jetbrains.space
swu-acm.jetbrains.space
walx.jetbrains.space

**Comment by bpystep** [comment]
@Ground-Zerro спасибо!

**Comment by bpystep** [comment]
@Ground-Zerro добавлял через кастом днс еще joinsport.jetbrains.space но не сработало. Через полное перенаправление траффика через VPN (wireguard) работает

**Comment by Ground-Zerro** [comment]
> Через полное перенаправление траффика через VPN (wireguard) работает

А что там у них за сервисы? Имею ввиду что не работает от джетбрэйнс?

К примеру Пайчарм не хотел работать, добавил в тоннель то что сейчас есть в списке (правда по доменам маршрутизация) и он завелся.

**Comment by bpystep** [comment]
> А что там у них за сервисы? Имею ввиду что не работает от джетбрэйнс?

git+task_manager+pipeline и прочее, если коротко то просто собственный github xD

Не пускает на сам сервис. С впн - проблем нет, но вот если в роутер (keenetic) закинуть машруты из domainmapper и использовать тот же впн, то все равно не пускает с той же самой ошибкой (см. скрин)

![Image](https://github.com/user-attachments/assets/9a278c4e-7aad-441d-9f20-db6d0eeba3e1)
