### ISSUE TITLE
Github Copilot

### ISSUE THREAD

**Issue by SocketSomeone** [Ground-Zerro/DomainMapper#42]
![image](https://github.com/user-attachments/assets/6fde82b4-da7e-4e0d-a63e-12a1240d4e07)
Не тянется Github Copilot

**Comment by Ground-Zerro** [comment]
Такое бывает, что Git коверкает ссылку с доменами его копайлота.
![gitcopilot](https://github.com/user-attachments/assets/f9f2adf8-3cbd-4681-8272-674d595973b2)
Пробуйте еще раз.
