### ISSUE TITLE
Некорректные зависимости проекта

### ISSUE THREAD

**Issue by DeapHy** [Ground-Zerro/DomainMapper#44]
Привет. При подтягивании зависимостей через requirements.txt обнаружил, что не хватает двух зависимостей. Обновленный файл выглядит так:

dnspython~=2.6.1
requests~=2.31.0
beautifulsoup4~=4.12.3
**colorama~=0.4.6
httpx~=0.27.2**

п.с. Сори что не через merge request, ни разу не занимался таким в публичных репах :D

**Comment by Ground-Zerro** [comment]
Привет.
Они есть в основной ветке, их нет в зависимостях ветки утилит. Не предполагал что зависимости будут брать оттуда, добавлю.
Спасибо.
