### ISSUE TITLE
mikrotik comment

### ISSUE THREAD

**Issue by ITNetSystem** [Ground-Zerro/DomainMapper#45]
Привет! можешь для микротика при формировании запросов - комментарий вынести отдельно, например если нужен то какой укажи имя, если не нужен то не добавлять или вообще его убрать.

**Comment by Ground-Zerro** [comment]
> можешь для микротика при формировании комментарий вынести отдельно, например если нужен то какой укажи имя, если не нужен то не добавлять или вообще его убрать.

Можно задать его в `config.ini` или просто нажать Enter и он останется пустым.
Или что-то другое имеется ввиду?

Не владею железкой этой компании. Насколько помню когда обсуждалось предложение по его добавлению писали, что строка `comment=""` является обязательной в синтаксисе CLI команды для добавления маршрута у микротика.

**Comment by Ground-Zerro** [comment]
ААА, посмотрел.
Сейчас он не запрашивается и формируется из списка проверяемых сервисов.
т.е. нужно предложить его ввести или оставить по выбору системы?

**Comment by ITNetSystem** [comment]
Параметр comment не обязательный в синтаксисе и его можно не задавать, я вообще не понимаю зачем человеку он понадобился, так как и так понятно по названию листа что это. У тебя реализовано так что я задаю имя листа и автоматически это имя присваивается к полю комментарий. Так вот или убрать его вообще или спрашивать нужен ли вам комментарий оставьте поле пустым если не нужно или введите имя.

**Comment by Ground-Zerro** [comment]
> Так вот или убрать его вообще или спрашивать нужен ли вам комментарий оставьте поле пустым если не нужно или введите имя.

Принято.

Скорее всего будет так: если не нужен или нужен какой-то специфичный то необходимо будет это задать это в  `config.ini`, если параметр не задан или не указано `n/no` будет формироваться так как сделано сейчас.

По времени не скажу, когда, но постараюсь не затягивать.

Требуется уточнение: текст `comment=""` вообще не нужен или просто в кавычках должно быть пусто?

**Comment by Ground-Zerro** [comment]
@ITNetSystem 
За недостатком времени сделал так:

в config.ini добавлена опция:
# комментарий - используется при сохранении IP-адресов в 'mikrotik' формате
# опции:
# пустое значение - оставить comment=%SERVICE_NAME% в строке
# off - убрать comment=%SERVICE_NAME% из строки
mk_comment = 

Комментарий будет добавляться всегда при запуске батником из сети, убрать его можно только при локальном запуске `main.py` при наличии рядом с ним `config.ini`

**Comment by Shaman2010** [comment]
> ...я вообще не понимаю зачем человеку он понадобился, так как и так понятно по названию листа что это...
Мне он понадобился для того, чтобы понимать, **откуда** у меня появилась эта запись в MikroTik, так как у меня несколько источников, которые пополняют список адресов, перенаправляемых через VPN
