### ISSUE TITLE
Не загружает маршруты из файла

### ISSUE THREAD

**Issue by Arean71** [Ground-Zerro/DomainMapper#47]
Добрый день!  У меня Keenetic 4.2.1
Пробовал подготавливать маршруты вразых форматах. Результат один - ошибка :"Не удалось импортировать маршруты из файла "domain-ip-resolve.bat"

В интерфейсе устройства предлагает : 
Вы можете загрузить список маршрутов из bat-файла операционной системы Windows.
Пример команды bat-файла: route ADD 157.0.0.0 MASK 255.0.0.0 157.55.80.1

![image](https://github.com/user-attachments/assets/8c5ba5be-a4d7-4a16-8f9c-9bcc8fbebb22)

bat файл подготовленный прикреплен
[domain-ip-resolve.zip](https://github.com/user-attachments/files/17465842/domain-ip-resolve.zip)

**Comment by Ground-Zerro** [comment]
После маски посдети должен быть IP шлюза. В этом случае, если VK это имя VPN интерфейса, достаточно указать 0.0.0.0
Для примера:
Вместо `route add 103.101.0.0 mask 255.255.0.0 VK` должен быть `route add 103.101.0.0 mask 255.255.0.0 0.0.0.0`

По какому из видео гайдов делался файл? Появилось таких довольно много и каждый на свой лад их презентует...
В случае с Кинетиком вообще все максимально просто, даже в .bat переименовывать не нужно, как это преподносят авторы.



https://github.com/user-attachments/assets/a9214c26-c420-4c52-ae1a-88f8faf92534
