### ISSUE TITLE
Крашается прога

### ISSUE THREAD

**Issue by komar3456** [Ground-Zerro/DomainMapper#49]
Запускаю скрипт мейн в файлах ничего не менял. С пустыми параметрами конфиг файла. Идет подбор какое-то время, потом прога вылетает, что-то красное вылезает, но не возможно прочитать. Файл не записывается. Python 3.13.0

**Comment by Ground-Zerro** [comment]
@komar3456 
Без вывода консоли не разобраться.

На windows запускается? Через батник? Или на какой-то Linux?

Если на винде - сначала запусти командную строку из меню пуск или другим способом и уже в ней запусти скрипт - останется лог с ошибками.
