### ISSUE TITLE
Просьба.

### ISSUE THREAD

**Issue by toxae1** [Ground-Zerro/DomainMapper#51]
Не могли бы вы добавить ещё один формат для сохранения для файла hosts. 
Ip domen
200.200.200.200 youtube.com
И если например у доменов один и тот же айпи тогда
200.200.200.200 youtube.com yt.com и так далее. 
По концовке выдавать исключительные ip и соответствующие им домены. 
Спасибо.

**Comment by Ground-Zerro** [comment]
В рамках DM к сожалению не получится.
Логика работы кода совершенно другая и построена на получении IP листа из DNS списка, затем фильтрации IP и пост обработки IP. В нем изначально не предусмотрены пары "домен - IP".
Если в DM что-то переделывать под этот запрос, то получится отдельная утилита, фактически написанная с нуля.

============
Развивая мысль.
В таком виде список будет состоять из оооочень длинных строк и будет совершенно не читаемым т.к. например на одном IP может быть десяток и более доменов, ровно также как один домен может иметь больше десятка IP-адресов.

**Comment by toxae1** [comment]
Благодарю Вас за расширенный ответ, всё предельно понятно. Ещё раз спасибо.
