### ISSUE TITLE
Mikrotik file in wrong encoding

### ISSUE THREAD

**Issue by Savanture** [Ground-Zerro/DomainMapper#54]
Файл, который формируется для Mikrotik (filetype = mikrotik), создаётся в кодировке UTF-8-BOM, которая не понимается устройством. Приходится вручную пересохранять файл в UTF-8. Поправьте, пожалуйста, кодировку файла.

**Comment by Ground-Zerro** [comment]
@Savanture 
Убрал BOM, [проверяйте](https://github.com/Ground-Zerro/DomainMapper/blob/main/main.py)
