### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by mshakurov** [Ground-Zerro/DomainMapper#55]
После обновления с примерно августовской версии теперь при запуске 
`python3  main.py`
получаю ошибку:

```
  File "main.py", line 508
    'mikrotik': lambda ip: f'/ip/firewall/address-list add list={mk_list_name}{f' comment="{comment(selected_service)}"' if mk_comment != "off" else ""} address={ip}/{subnet}',
                                                                                  ^
SyntaxError: invalid syntax
```

Клонировано в чистую папку.
OS: 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.6 LTS"

**Comment by mshakurov** [comment]
`python3 is already the newest version (3.8.2-0ubuntu2).`

дело видимо в том, что в ubuntu 20.04 focal поддерживается только 3.8.2 (репозитории ubuntu указывают на максимально 3.8.2)

с этим как-то надо обходиться... вручную поставил все версии, от 3.9 до 3.13, и ни с одной не работает, например:

```
python3.13 main.py
Traceback (most recent call last):
  File "/root/DomainMapper/main.py", line 9, in <module>
    import dns.asyncresolver
ModuleNotFoundError: No module named 'dns'

```

и не работает `pip install -r requirements.txt` ни с одной версией от 3.9 до 3.13

```
python3.13 -m  pip install -r requirements.txt

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3/dist-packages/pip/__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/cmdoptions.py", line 19, in <module>
    from distutils.util import strtobool
ModuleNotFoundError: No module named 'distutils'

```

пришлось откатиться твой репозиторий до комита 9 ноября (ebc21747a660ffa8a2) и тогда скрипт main.py заработал с питоном 3.8.2.

**Comment by Ground-Zerro** [comment]
DM изначально писался на 3.9, как себя ведет на прошлых версиях не проверял.
Однако на Ubuntu 20.04 у меня все заводилось, хотя давно там не тестил, надо бы перепроверить...

````
{mk_list_name}{f' comment="{comment(selected_service)}"' if mk_comment != "off" else ""}
                          ^
````
Здесь пробел нужен т.к. этого требует синтаксис команды для mikrotic и конструкция кода должна учитывать настройку `mk_comment` в конфиге, если сделать так:
````
{mk_list_name} {f'comment="{comment(selected_service)}"' if mk_comment != "off" else ""}
                       ^
````
в команде будет лишний пробел и роутер ее не поймет.

Спасибо за обратную связь. @mshakurov @interhin
