### ISSUE TITLE
Ошибка выполнения main.py

### ISSUE THREAD

**Issue by drts-sv** [Ground-Zerro/DomainMapper#56]
запуск win.bat под windows 11 приводит к выводу сообщения:

```
Запускаем...
  File "C:\Users\drts\Desktop\Domain Mapper\main.py", line 508
    'mikrotik': lambda ip: f'/ip/firewall/address-list add list={mk_list_name}{f' comment="{comment(selected_service)}"' if mk_comment != "off" else ""} address={ip}/{subnet}',
                                                                                  ^^^^^^^
SyntaxError: f-string: expecting '}'
Ошибка выполнения main.py.
Press any key to continue . . .
```

**Comment by Vlad15lav** [comment]
Попробуйте исправить скрипт main.py.

Строка 508:
`'mikrotik': lambda ip: f'/ip/firewall/address-list add list={mk_list_name}' + (f' comment="{comment(selected_service)}"' if mk_comment != "off" else "") + f' address={ip}/{subnet}',`

Строка 529:
`'mikrotik': lambda ip: f'/ip/firewall/address-list add list={mk_list_name}' + (f' comment="{comment(selected_service)}"' if mk_comment != "off" else "") + f' address={mix_formatter(ip)}',`

**Comment by Ground-Zerro** [comment]
@Vlad15lav
Внес предложенные исправления.
Спасибо.

@drts-sv 
Нужна проверка т.к. у меня скрипт и так работал, не понимаю откуда проблема появилась, перед публикацией всегда проверяю.
