### ISSUE TITLE
YouTube хосты которые не грузятся

### ISSUE THREAD

**Issue by phenomenonRT** [Ground-Zerro/DomainMapper#59]
Прошу добавить эти хосты
<details>
  <summary>Хосты</summary>

> rr1---sn-4g5lznl6.googlevideo.com
> rr1---sn-5go7ynl6.googlevideo.com
> rr1---sn-5goeenes.googlevideo.com
> rr1---sn-5hne6nsr.googlevideo.com
> rr1---sn-n4v7snls.googlevideo.com
> rr1---sn-q4fzen7s.googlevideo.com
> rr2---sn-n4v7snse.googlevideo.com
> rr2---sn-ntq7yney.googlevideo.com
> rr3---sn-hgn7rnee.googlevideo.com
> rr3---sn-hgn7rnls.googlevideo.com
> rr3---sn-o097znz7.googlevideo.com
> rr3---sn-q4flrnld.googlevideo.com
> rr4---sn-5goeenez.googlevideo.com
> rr4---sn-o097znsd.googlevideo.com
> rr4---sn-q4fl6n6y.googlevideo.com
> rr5---sn-5go7ynld.googlevideo.com
> rr5---sn-ntqe6n76.googlevideo.com
> rr5---sn-q4flrnee.googlevideo.com

Просто ip для проверки базы

> 172.217.132.70
> 74.125.166.199
> 74.125.157.232
> 172.217.134.137
> 173.194.140.169
> 74.125.111.74
> 74.125.173.38
> 172.217.134.198
> 74.125.109.167
> 74.125.111.9
> 173.194.28.10
> 173.194.164.40

</details>

> И может это тоже использовать? https://github.com/vFee9l/Bloack-ads/blob/main/YTads.txt

> https://github.com/search?q=.googlevideo.com&type=repositories
> https://github.com/CureSaba/YouTubeStreamer/blob/main/YouTube%20streamer.ipynb

**Comment by Ground-Zerro** [comment]
> rr1---sn-4g5lznl6.googlevideo.com
> rr1---sn-5go7ynl6.googlevideo.com
> rr1---sn-5goeenes.googlevideo.com
> rr1---sn-5hne6nsr.googlevideo.com
> rr1---sn-n4v7snls.googlevideo.com
> rr1---sn-q4fzen7s.googlevideo.com
> rr2---sn-n4v7snse.googlevideo.com
> rr2---sn-ntq7yney.googlevideo.com
> rr3---sn-hgn7rnee.googlevideo.com
> rr3---sn-hgn7rnls.googlevideo.com
> rr3---sn-o097znz7.googlevideo.com
> rr3---sn-q4flrnld.googlevideo.com
> rr4---sn-5goeenez.googlevideo.com
> rr4---sn-o097znsd.googlevideo.com
> rr4---sn-q4fl6n6y.googlevideo.com
> rr5---sn-5go7ynld.googlevideo.com
> rr5---sn-ntqe6n76.googlevideo.com
> rr5---sn-q4flrnee.googlevideo.com

Добавил

> И может это тоже использовать? https://github.com/vFee9l/Bloack-ads/blob/main/YTads.txt

Посмотрел, объединил. На алиасы не проверял. К чести этого репозитория всего полторы сони припаркованных (не активных) домена.

> https://github.com/CureSaba/YouTubeStreamer/blob/main/YouTube%20streamer.ipynb

Что это, зачем нужно и как использовать - не понял.

> https://github.com/search?q=.googlevideo.com&type=repositories

Форсить руками весь гит, выбирая домены из сотен списков, сравнивая их друг с другом, проверять на дубли, деллигированность и алисасы - **нет**, уж извините.

Если есть интерес можете сами поиграться с [subdomain](https://github.com/Ground-Zerro/DomainMapper/tree/main/utilities), он хотя-бы Алиасы сразу отсеивает.
Прогнал `googlevideo.com` выпало `А` 6378 записей, исключая CNAME, AAAA, MX types. Из них 166 припаркованных.
Или можно напрямую попробовать ресурс [rapiddns](https://rapiddns.io/subdomain).

**Comment by phenomenonRT** [comment]
rapiddns не работает. Есть вопрос на счет того что бы сделать расширение которое собирало домены и под домены которые нельзя найти через подобное https://www.vedbex.com/subdomain-finder.

https://chromewebstore.google.com/detail/ipvfoo/ecanpcehffngcegjmadlcijfolapggal

**Comment by Ground-Zerro** [comment]
> rapiddns не работает

Да, он то работает то нет. То задумывается на второй странице и подвисает на полчаса час. То за ДДОС две открытых вкладки принимает и блочит. То без VPN не открывается. Некоммерческий проект, что взять..
Но хорош он своей базой размером более чем на 5 миллиардов доменов.

> Есть вопрос на счет того что бы сделать расширение которое собирало домены и под домены которые нельзя найти через подобное https://www.vedbex.com/subdomain-finder

Слабенький какой-то ресурс, для `googlevideo.com` всего 6 субдоменов нашел.
Предлагайте если есть достойные кандидаты, парсер нарисовать не особо сложно. Однако расширения для браузеров это не ко мне - не умею.

**Comment by phenomenonRT** [comment]
Ужас что творит сейчас гугл, еще домен который не грузится rr1---sn-8ph2xajvh-n8vs.googlevideo.com
