### ISSUE TITLE
Custom DNS list

### ISSUE THREAD

**Issue by TheGette** [Ground-Zerro/DomainMapper#61]
Я правильно понимаю, что в этом файле достаточно просто указать ссылку на какой-то сайт или нужно еще что-то добавить?
Пример: rutracker.net, www.instagram.com и тд

**Comment by Ground-Zerro** [comment]
> Я правильно понимаю, что в этом файле достаточно просто указать ссылку на какой-то сайт

Да, все верно.
Единственное - нужно указать один адрес на одной строчке, запятых и т.п. не нужно, пример:
```
rutracker.net
www.instagram.com
```
