### ISSUE TITLE
Ошибки import could not be resolved

### ISSUE THREAD

**Issue by dobriys** [Ground-Zerro/DomainMapper#63]
Пытаюсь выполнить main.py и получаю 2 ошибки:

```
Import "dns.asyncresolver" could not be resolved
Import "httpx" could not be resolved
```

requirements  выполнил. Mac OS 15.1.1 (24B91)

Что сделать чтоб выполнялось? Я в питоне совсем ноль, не понимаю что ему нужно.

**Comment by Ground-Zerro** [comment]
OS Windows?
Попробуй сделать [как написано здесь](https://github.com/Ground-Zerro/DomainMapper/tree/main/Windows). Подтянутся зависимости и Python.

**Comment by dobriys** [comment]
> OS Windows? Попробуй сделать [как написано здесь](https://github.com/Ground-Zerro/DomainMapper/tree/main/Windows). Подтянутся зависимости и Python.

Нет. Ось MAC OS 15.1.1 
При этом, для пробы, пакет dnspython я переустановил вручную.

**Comment by Ground-Zerro** [comment]
> MAC OS 15.1.1

Совсем нет опыта с этой ОС.

Может проблема в версии? Нужна не ниже 3.12.

**Comment by dobriys** [comment]
> Может проблема в версии? Нужна не ниже 3.12.

Python 3.12.5

Запускаю вот так:
`stanislavbayata@MacBook-Pro-Stanislav DomainMapper % python3 main.py` 
И получаю вот это:         
`Traceback (most recent call last):
  File "/Users/stanislavbayata/Downloads/DomainMapper/main.py", line 9, in <module>
    import dns.asyncresolver
ModuleNotFoundError: No module named 'dns'`

Понять бы почему он не подтягивает этот модуль. Ведь он именно не подтягивает его или я ошибаюсь?

**Comment by dobriys** [comment]
Разобрался. Все новые пакеты падали по пути 
`/usr/local/lib/**python3.10**/site-packages/`
а запуск `python3 main.py` искал пакеты по пути
`/usr/local/lib/**python3.12**/site-packages/`
Докачал недостающие пакеты и перенес копи-пастом всё в нужную папку и заработало. Может есть решение сделать это в терминале, но как смог )))
