### ISSUE TITLE
Dockerfile did not complete successfully: exit code: 100

### ISSUE THREAD

**Issue by neverfan** [Ground-Zerro/DomainMapper#66]
При запуске в docker через команду из документации:

`curl -L -s "https://raw.githubusercontent.com/Ground-Zerro/DomainMapper/refs/heads/main/dm-docker.sh" > /tmp/dm-docker.sh && chmod +x /tmp/dm-docker.sh && sh /tmp/dm-docker.sh`

ERROR: failed to solve: process "/bin/sh -c apt-get update &&     apt-get install -y software-properties-common &&     add-apt-repository -y ppa:deadsnakes/ppa &&     apt-get update &&     apt-get install -y python3.12 python3.12-venv python3.12-distutils &&     rm -rf /var/lib/apt/lists/*" did not complete successfully: exit code: 100

**Comment by Ground-Zerro** [comment]
> При запуске в docker через команду из документации:

Исправлено.

Генерация контейнера очень долгая т.к. Python компилится из исходников...
Как этим докером управлять я понятия не имею.

**Вопрос:**
Не легче просто запустить `main.py` чем городить весь этот огород?

**Comment by neverfan** [comment]
> Не легче просто запустить main.py - файл на 30.8 KB, чем городить весь этот огород?

Правильнее запускать в контейнере, т.к. локальное окружение у всех может быть разное
