### ISSUE TITLE
Не работает instagram

### ISSUE THREAD

**Issue by absurd121** [Ground-Zerro/DomainMapper#67]
Резолвил для роутера keenetic сервисы chatgpt, bing, youtube, instagram по инструкции - [git](https://github.com/Ground-Zerro/DomainMapper/discussions/50#discussioncomment-11266339)
Все заработало, кроме инстаграма. Может список доменов устарел/не полный?
На роутере DoT яндекс, wireguard.

**Comment by Ground-Zerro** [comment]
> Может список доменов устарел/не полный?

На роутере используется шифрованные DNS сервера, а остальные, особенно от провайдера, отключены/удалены?
Поясню: Многие домашние провайдеры подменяют ответы DNS сервера (если его трафик не зашифрован) к инстаграму заворачивая их на несуществующий адрес (локалхост или сами на себя).

Хотя вполне может быть, что чего-то не хватает. Какого-нибудь субдомена.
Если удастся выяснить - дайте знать, добавлю в список.

PS
Я использую список из репозитория DM, но без субдоменов - все работает. 
Правда другой способ "точечной" маршрутизации используется (ipSec+AGH), где все субдомены учитываются автоматически. В случае со статическим маршрутами так не получится.

**Comment by Ground-Zerro** [comment]
@absurd121 

Да, субдоменов небыло.
Добавил что нашел с двух основных доменов, 420 штук получилось.
Прогони DM и закинь в роутер.
