### ISSUE TITLE
GH workflow

### ISSUE THREAD

**Issue by shevernitskiy** [Ground-Zerro/DomainMapper#7]
Можно добавить воркфлоу с переодическим триггером (скажем раз в день), который будет запускать скрипт и обновлять полученные ip в папочке в репе.
Тогда можно выкладывать ссылки на эти файлы, потому что они всегда будут актуальными.

**Comment by Ground-Zerro** [comment]
> Можно добавить воркфлоу с переодическим триггером (скажем раз в день), который будет запускать скрипт и обновлять полученные ip в папочке в репе.
> Тогда можно выкладывать ссылки на эти файлы, потому что они всегда будут актуальными.

Имеется ввиду выкладывать ссылки на файлы статических маршрутов или просто IP листы?

Это лишено смысла из-за особенностей работы DNS.

Простым языком:

Если ваш VPN условно находится в Нидерландах, а вы в Москве то DNS сервер разрешит имя например "instagram.com" в разные IP адреса, т.е. для клиента в Нидерландах он вернет один IP адрес, а для клиента из Москвы другой.
Многие сервисы используют хостинг "cloudflare" и аналогичные которые для одного и того же DNS имени могут возвращать разные IP адреса в зависимости от геопозиции клиента, текущей нагрузки на сервер, времени суток, типа устройства и других факторов. В итоге одно и тоже DNS имя в разный момент времени для разных людей выдаст разные IP адреса. Это может произойти даже если ваш IP-адрес и местоположение не менялись. Например "chatgpt.com" может для одного домашнего ПК выдать один IP, а для второго домашнего ПК стоящего рядом с первым уже другой.

Есть сервисы IP которых постоянны или меняются не очень часто, но это встречается все реже.

Комьюнити рекомендует перенаправлять трафик к DNS серверу также через используемый VPN и резолвить DNS имена на той машине с которой с ними работать будут работать.

В этом и смысл DomainMapper, чтобы каждый мог его скачать и создать список IP адресов именно для себя.

PS
В моем регионе магистральный провайдер вообще начал полностью блокировать протокол quic и простая точечная маршрутизация потеряла смысл, вынуждая обращаться к более сложным решениям.
