### ISSUE TITLE
Добавить недостающий DNS Discord

### ISSUE THREAD

**Issue by Myddll** [Ground-Zerro/DomainMapper#72]
После переустановки винды столкнулся с проблемой того, что не могу скачать дискорд, остался старый установочник, увидеть обновления он может, но не может стянуть. Посмотрел, там не хватает одного DNS дискорда **stable.dl2.discordapp.net**

**Comment by Ground-Zerro** [comment]
> stable.dl2.discordapp.net

Добавлен.
